server:
  port: 8182

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: ALWAYS
    health:
      show-details: always

logging:
  level:
    # root: warn
    # org.springframework: warn
    # org.springframework.boot: warn
    # org.hibernate.SQL: off
    # org.hibernate.type.descriptor.sql: off
    # com.zaxxer.hikari: error
    # org.apache.coyote.http11: off
    root: off
    org.springframework: off
    org.springframework.boot: off
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql: off
    com.zaxxer.hikari: error
    org.apache.coyote.http11: off

product-service:
  product-reservation-request-topic-name: product-reservation-request
  product-reservation-response-topic-name: product-reservation-response
  outbox-scheduler-fixed-rate: 50
  outbox-scheduler-initial-delay: 1000
  outbox-scheduler-batch-size: 100
  outbox-processing-timeout-minutes: 5
  outbox-cleaner-cron: "@midnight"
  outbox-cleaner-batch-size: 100
  inbox-scheduler-fixed-rate: 50
  inbox-retry-scheduler-fixed-rate: 1000
  inbox-max-retry-count: 3
  inbox-batch-size: 200

spring:
  main:
    banner-mode: off
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        default_schema: product
  datasource:
    url: jdbc:mysql://localhost:13306/product?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-test-query: SELECT 1
      pool-name: ProductServiceHikariPool
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

kafka-config:
  bootstrap-servers: ${KAFKA_CONFIG_BOOTSTRAP_SERVERS:localhost:19092, localhost:19093, localhost:19094}
  schema-registry-url-key: schema.registry.url
  schema-registry-url: ${KAFKA_CONFIG_SCHEMA_REGISTRY_URL:http://localhost:18081}

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.UUIDSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  acks: all
  batch-size: 16384
  linger-ms: 5
  compression-type: none
  request-timeout-ms: 60000
  retry-count: 5

kafka-consumer-config:
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
  product-reservation-consumer-group-id: product-reservation-topic-consumer
  customer-group-id: customer-topic-consumer
  auto-offset-reset: earliest
  specific-avro-reader-key: specific.avro.reader
  specific-avro-reader: true
  batch-listener: true
  auto-startup: true
  concurrency-level: 10
  session-timeout-ms: 10000
  heartbeat-interval-ms: 3000
  max-poll-interval-ms: 300000
  max-poll-records: 500
  max-partition-fetch-bytes-default: 1048576
  max-partition-fetch-bytes-boost-factor: 1
  poll-timeout-ms: 150

---
spring:
  config:
    activate:
      on-profile: docker
  flyway:
    enabled: false