/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.commerce.platform.kafka.order.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum ProductReservationOrderStatus implements org.apache.avro.generic.GenericEnumSymbol<ProductReservationOrderStatus> {
  PENDING, PAID, CANCELLED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ProductReservationOrderStatus\",\"namespace\":\"com.commerce.platform.kafka.order.avro.model\",\"symbols\":[\"PENDING\",\"PAID\",\"CANCELLED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
