/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.commerce.platform.kafka.order.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum ProductReservationStatus implements org.apache.avro.generic.GenericEnumSymbol<ProductReservationStatus> {
  APPROVED, REJECTED, BOOKED, CANCELLED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ProductReservationStatus\",\"namespace\":\"com.commerce.platform.kafka.order.avro.model\",\"symbols\":[\"APPROVED\",\"REJECTED\",\"BOOKED\",\"CANCELLED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
